name = "genshin-search-bot"
type = 'javascript'
workers_dev = true

[[kv_namespaces]]
binding = "DB"
id = "948fd6d2c37d47b193f4e6461c3417d3"
preview_id = "948fd6d2c37d47b193f4e6461c3417d3"

[dev]
port = 3000

[build]
command = "npm run build"
[build.upload]
format = "service-worker"